server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service  #匹配后提供路由的服务地址
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由  **代表通配符的作用
          # 过滤
          #filters:
          #  - AddRequestHeader=X-Request-red, blue
        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service  #匹配后提供路由的服务地址
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
              #- After=2017-01-20T17:42:47.789-07:00[America/Denver]
              #- Before=2017-01-20T17:42:47.789-07:00[America/Denver]
              #- Cookie=username,zzyy
              #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数  curl http://localhost:9527/payment/lb -H "X-Request-Id:123"
              #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
#            - Cookie=username,zzyy  #curl http://localhost:9527/payment/lb --cookie "username=zzyy" cmd命令窗口输入访问


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#      单机版
      defaultZone: http://eureka7001.com:7001/eureka/